-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
-- S.O. server:                  
-- HeidiSQL Versione:            10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dump dei dati della tabella public.serviziosanitarioprovinciale: 105 rows
/*!40000 ALTER TABLE "serviziosanitarioprovinciale" DISABLE KEYS */;
INSERT INTO "serviziosanitarioprovinciale" ("provincia") VALUES
	('AL'),
	('AN'),
	('AO'),
	('AR'),
	('AP'),
	('AT'),
	('AV'),
	('BA'),
	('BT'),
	('BL'),
	('BN'),
	('BG'),
	('BI'),
	('BO'),
	('BZ'),
	('BS'),
	('BR'),
	('CA'),
	('CL'),
	('CB'),
	('CE'),
	('CT'),
	('CZ'),
	('CH'),
	('CO'),
	('CS'),
	('CR'),
	('KR'),
	('CN'),
	('EN'),
	('FM'),
	('FE'),
	('FI'),
	('FG'),
	('FR'),
	('GE'),
	('GO'),
	('GR'),
	('IM'),
	('IS'),
	('SP'),
	('AQ'),
	('LT'),
	('LE'),
	('LC'),
	('LI'),
	('LO'),
	('LU'),
	('MC'),
	('MN'),
	('MS'),
	('MT'),
	('ME'),
	('MI'),
	('MO'),
	('MB'),
	('NA'),
	('NO'),
	('NU'),
	('OR'),
	('PD'),
	('PA'),
	('PR'),
	('PV'),
	('PG'),
	('PU'),
	('PE'),
	('PC'),
	('PI'),
	('PT'),
	('PN'),
	('PZ'),
	('PO'),
	('RG'),
	('RA'),
	('RC'),
	('RE'),
	('RI'),
	('RN'),
	('RM'),
	('RO'),
	('SA'),
	('SS'),
	('SV'),
	('SI'),
	('SR'),
	('SO'),
	('TA'),
	('TE'),
	('TR'),
	('TO'),
	('TP'),
	('TN'),
	('TV'),
	('TS'),
	('UD'),
	('VA'),
	('VE'),
	('VB'),
	('VC'),
	('VR'),
	('VV'),
	('VI'),
	('VT'),
	('FC');
/*!40000 ALTER TABLE "serviziosanitarioprovinciale" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
